baseurl = "https://toastit.dev"
metaDataFormat = "toml"
title = "ToastIT"
theme = "ananke"
enableRobotsTXT = true
Paginate = 15

googleAnalytics = 'G-PNF7X4NP00'
disqusShortname = 'windosgithub'

[taxonomies]
  tags = 'tag'
  series = 'series'

[permalinks]
  blog = '/:year/:month/:day/:slug'

contentDir = "content"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "blog"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "tag"
    weight = 2

  [[menu.main]]
    name = "Feed"
    url = "index.xml"
    weight = 3

[author]
  name = 'Josh King'

[params]
  introTitle = "Josh King"
  introSubtitle = "Geek, Father, Walking Helpdesk"
  introPhoto = "/avatar.jpg"
  logo = "/toastit-logo.png"

  background_color_class = "bg-black"
  author = "Josh King"
  site_logo = "/toastit-logo.png"
  recent_posts_number = 5

  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Josh King · All rights reserved"
  favicon = "/favicon.png"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-300"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Open Graph
  description = "Geek, Father, Walking Helpdesk"
  images = ['site_hero.jpg']
  title = 'ToastIT.dev - Josh King'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = ""
  mastodon = "https://mastodon.nz/@windos"
  twitter = "https://twitter.com/WindosNZ"
  linkedin = "https://linkedin.com/in/windos"
  github = "https://github.com/Windos"
  youtube = "https://www.youtube.com/c/JoshuaKingSolari"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

[[params.ananke_socials]]
name = "mastodon"
url = "https://mastodon.nz/@windos"
rel = "me noopener"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/WindosNZ"

[[params.ananke_socials]]
name = "linkedin"
url = "https://linkedin.com/in/windos"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/Windos"

[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/c/JoshuaKingSolari"
